# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Item.create!(title: "début", img: "http://upload.wikimedia.org/wikipedia/commons/7/7c/Aspect_ratio_16_9_example.jpg", url: "http://google.com", vues: 100)
Item.create!(title: "Google is the best something", img: "http://upload.wikimedia.org/wikipedia/commons/7/7c/Aspect_ratio_16_9_example.jpg", url: "http://google.com", vues: 100)
Item.create!(title: "Google is the best something", img: "http://upload.wikimedia.org/wikipedia/commons/7/7c/Aspect_ratio_16_9_example.jpg", url: "http://google.com", vues: 100)
Item.create!(title: "Google is the best something", img: "http://upload.wikimedia.org/wikipedia/commons/7/7c/Aspect_ratio_16_9_example.jpg", url: "http://google.com", vues: 100)
Item.create!(title: "Google is the best something", img: "http://upload.wikimedia.org/wikipedia/commons/7/7c/Aspect_ratio_16_9_example.jpg", url: "http://google.com", vues: 100)
Item.create!(title: "Google is the best something", img: "http://upload.wikimedia.org/wikipedia/commons/7/7c/Aspect_ratio_16_9_example.jpg", url: "http://google.com", vues: 100)
Item.create!(title: "Google is the best something", img: "http://upload.wikimedia.org/wikipedia/commons/7/7c/Aspect_ratio_16_9_example.jpg", url: "http://google.com", vues: 100)
Item.create!(title: "Google is the best something", img: "http://upload.wikimedia.org/wikipedia/commons/7/7c/Aspect_ratio_16_9_example.jpg", url: "http://google.com", vues: 100)
Item.create!(title: "Google is the best something", img: "http://upload.wikimedia.org/wikipedia/commons/7/7c/Aspect_ratio_16_9_example.jpg", url: "http://google.com", vues: 100)
Item.create!(title: "Google is the best something", img: "http://upload.wikimedia.org/wikipedia/commons/7/7c/Aspect_ratio_16_9_example.jpg", url: "http://google.com", vues: 100)
Item.create!(title: "Google is the best something", img: "http://upload.wikimedia.org/wikipedia/commons/7/7c/Aspect_ratio_16_9_example.jpg", url: "http://google.com", vues: 100)
Item.create!(title: "Google is the best something", img: "http://upload.wikimedia.org/wikipedia/commons/7/7c/Aspect_ratio_16_9_example.jpg", url: "http://google.com", vues: 100)
Item.create!(title: "Google is the best something", img: "http://upload.wikimedia.org/wikipedia/commons/7/7c/Aspect_ratio_16_9_example.jpg", url: "http://google.com", vues: 100)
Item.create!(title: "Google is the best something", img: "http://upload.wikimedia.org/wikipedia/commons/7/7c/Aspect_ratio_16_9_example.jpg", url: "http://google.com", vues: 100)
Item.create!(title: "Google is the best something", img: "http://upload.wikimedia.org/wikipedia/commons/7/7c/Aspect_ratio_16_9_example.jpg", url: "http://google.com", vues: 100)
Item.create!(title: "Google is the best something", img: "http://upload.wikimedia.org/wikipedia/commons/7/7c/Aspect_ratio_16_9_example.jpg", url: "http://google.com", vues: 100)
Item.create!(title: "Google is the best something", img: "http://upload.wikimedia.org/wikipedia/commons/7/7c/Aspect_ratio_16_9_example.jpg", url: "http://google.com", vues: 100)
Item.create!(title: "Google is the best something", img: "http://upload.wikimedia.org/wikipedia/commons/7/7c/Aspect_ratio_16_9_example.jpg", url: "http://google.com", vues: 100)
Item.create!(title: "Google is the best something", img: "http://upload.wikimedia.org/wikipedia/commons/7/7c/Aspect_ratio_16_9_example.jpg", url: "http://google.com", vues: 100)
Item.create!(title: "Google is the best something", img: "http://upload.wikimedia.org/wikipedia/commons/7/7c/Aspect_ratio_16_9_example.jpg", url: "http://google.com", vues: 100)
Item.create!(title: "Google is the best something", img: "http://upload.wikimedia.org/wikipedia/commons/7/7c/Aspect_ratio_16_9_example.jpg", url: "http://google.com", vues: 100)
Item.create!(title: "Google is the best something", img: "http://upload.wikimedia.org/wikipedia/commons/7/7c/Aspect_ratio_16_9_example.jpg", url: "http://google.com", vues: 100)
Item.create!(title: "Google is the best something", img: "http://upload.wikimedia.org/wikipedia/commons/7/7c/Aspect_ratio_16_9_example.jpg", url: "http://google.com", vues: 100)
Item.create!(title: "Google is the best something", img: "http://upload.wikimedia.org/wikipedia/commons/7/7c/Aspect_ratio_16_9_example.jpg", url: "http://google.com", vues: 100)
Item.create!(title: "Google is the best something", img: "http://upload.wikimedia.org/wikipedia/commons/7/7c/Aspect_ratio_16_9_example.jpg", url: "http://google.com", vues: 100)
Item.create!(title: "Google is the best something", img: "http://upload.wikimedia.org/wikipedia/commons/7/7c/Aspect_ratio_16_9_example.jpg", url: "http://google.com", vues: 550)
Item.create!(title: "Google is the best something", img: "http://upload.wikimedia.org/wikipedia/commons/7/7c/Aspect_ratio_16_9_example.jpg", url: "http://google.com", vues: 100)
Item.create!(title: "Google is the best something", img: "http://upload.wikimedia.org/wikipedia/commons/7/7c/Aspect_ratio_16_9_example.jpg", url: "http://google.com", vues: 100)
Item.create!(title: "Google is the best something", img: "http://upload.wikimedia.org/wikipedia/commons/7/7c/Aspect_ratio_16_9_example.jpg", url: "http://google.com", vues: 100)
Item.create!(title: "Google is the best something", img: "http://upload.wikimedia.org/wikipedia/commons/7/7c/Aspect_ratio_16_9_example.jpg", url: "http://google.com", vues: 100)
Item.create!(title: "Google is the best something", img: "http://upload.wikimedia.org/wikipedia/commons/7/7c/Aspect_ratio_16_9_example.jpg", url: "http://google.com", vues: 100)
Item.create!(title: "Google is the best something", img: "http://upload.wikimedia.org/wikipedia/commons/7/7c/Aspect_ratio_16_9_example.jpg", url: "http://google.com", vues: 100)
Item.create!(title: "Google is the best something", img: "http://upload.wikimedia.org/wikipedia/commons/7/7c/Aspect_ratio_16_9_example.jpg", url: "http://google.com", vues: 100)
Item.create!(title: "Google is the best something", img: "http://upload.wikimedia.org/wikipedia/commons/7/7c/Aspect_ratio_16_9_example.jpg", url: "http://google.com", vues: 100)
Item.create!(title: "fin", img: "http://upload.wikimedia.org/wikipedia/commons/7/7c/Aspect_ratio_16_9_example.jpg", url: "http://google.com", vues: 100)
